owner = "neutron1phx0sz708k3t6xdnyc98hgkyhra4tp44et5s68"
atom_denom = "ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9"
datom_denom = "factory/neutron1k6hr0f83e7un2wjf29cspk7j69jrnskk65k3ek2nj9dztrlzpj6q00rtsa/udatom"
drop_liquid_staker_addr = "neutron16m3hjh7l04kap086jgwthduma0r5l0wh8kc6kaqk92ge9n5aqvys9q6lxr"
drop_liquid_unstaker_addr = "neutron16m3hjh7l04kap086jgwthduma0r5l0wh8kc6kaqk92ge9n5aqvys9q6lxr"
drop_withdrawal_manager_addr = "neutron1gcklauurx4ckyp0t8a6axl0500vy3n09y5utpspjg8ruxnln8erq2uumck"
voucher_addr = "neutron1f4c2l9u8yekp99mexyhf7wxgrq3gjtuzgrqe90xaq75v7quulptqzef6up"
neutron_dao_addr = "neutron1phx0sz708k3t6xdnyc98hgkyhra4tp44et5s68"
security_dao_addr = "neutron1phx0sz708k3t6xdnyc98hgkyhra4tp44et5s68"