owner = "neutron1r3ur0g2ymhax7v79sdyhnts6tqakeey3z6jwjt" # Updated
usdc_ntrn_lp_denom = "factory/neutron1czkddm6xqyfa6ukzxqmf65tl4tudry4kve0n8fs5yfc8g6zv52lqznmnnl/astroport/share" # Updated
usdc_ntrn_pool_addr = "neutron1czkddm6xqyfa6ukzxqmf65tl4tudry4kve0n8fs5yfc8g6zv52lqznmnnl" # Updated
usdc_dntrn_pool_addr = "neutron1kpschkazjaq64ufet9lr9g8fdn0k67eufkuljztxdr36pq87wans8hwgez" # Updated
ntrn_denom = "untrn" # Unchanged
dntrn_denom = "factory/neutron1lzfk4aj26jz7gd3c4umxah9d22ezy8xfql677kev37vd0mq8y3tsn78saz/udntrn" # Unchanged
usdc_denom = "factory/neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2/usdc" # Updated
drop_liquid_staker_addr = "neutron18ecx6f2ywwnfxsql2l98jscw97lezczx8ax0g5wp8uj9rm95m0ls798cdq" # Unchanged
pool_max_spread = "0.5" # 
neutron_dao_addr = "neutron1yw4xvtc43me9scqfr2jr2gzvcxd3a9y4eq7gaukreugw2yd2f8ts8g30fq" # Neutron Main DAO
security_dao_addr = "neutron10h9stc5v6ntgeygf5xf945njqq5h32r54rf7kf" # Unchanged
double_sided_min = "0.5" #
double_sided_max = "2" #
authorizations_allowed_list = [
    "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf",
    "neutron1hl9vrr0k0l2pz62v343f50v0djm87dzhvxjtca",
]