owner = ""
ntrn_denom = "untrn"
dntrn_denom = ""
bootstrap_ntrn_dntrn_receive_addr = ""
drop_liquid_staker_addr = ""
drop_liquid_unstaker_addr = ""
drop_withdrawal_manager_addr = ""
voucher_addr = ""
neutron_dao_addr = ""
security_dao_addr = ""