owner               = ""
ntrn_denom          = ""
dntrn_denom         = ""
astroport_pool_addr = ""
astroport_lp_denom  = ""
pool_max_spread     = ""
neutron_dao_addr    = ""
security_dao_addr   = ""
expected_pool_ratio_min    = ""
expected_pool_ratio_max    = ""
