owner = "neutron1r3ur0g2ymhax7v79sdyhnts6tqakeey3z6jwjt" # Updated
ntrn_denom = "untrn" # Unchanged
dntrn_denom = "factory/neutron1lzfk4aj26jz7gd3c4umxah9d22ezy8xfql677kev37vd0mq8y3tsn78saz/udntrn" # Updated
astroport_pool_addr = "neutron1lm6c6g5sm9jgt55x5dca3jlqxxsdal7j4ylemfsa7h6ed725s73ql3hdyx" # NTRN-dNTRN
astroport_lp_denom = "factory/neutron1lm6c6g5sm9jgt55x5dca3jlqxxsdal7j4ylemfsa7h6ed725s73ql3hdyx/astroport/share" # Updated
pool_max_spread = "0.5" # Unchanged
neutron_dao_addr = "neutron1yw4xvtc43me9scqfr2jr2gzvcxd3a9y4eq7gaukreugw2yd2f8ts8g30fq" # Neutron Main DAO
security_dao_addr = "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf"
expected_pool_ratio_min = "0.5" # Unchanged
expected_pool_ratio_max = "2" # Unchanged
authorizations_allowed_list = [ # Unchanged
    "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf",
    "neutron1hl9vrr0k0l2pz62v343f50v0djm87dzhvxjtca",
]

## Mnemonics
# devnet-2-owner
# spatial firm unfair swarm cash siren abuse physical crumble useful path pink guilt virus agent cherry tip smile blind police wrist health summer spell
# neutron1r3ur0g2ymhax7v79sdyhnts6tqakeey3z6jwjt