owner = "neutron1ayw8xtxkty5cfzx44z6vxpevmtudg2n3d2sfz8" # Updated this to Udit's dev wallet

# Token denomination
ntrn_denom = "untrn"

# We are receiving a total of 50M NTRN from the neutron DAO

# Valence Program 2: Instant liquid stake
vp2_instant_ls_receiver_address="neutron1pdkwssx28zp93p4pucfgy05dvrvcsttpktgphrwxqvlxw3chxcksuuejr8" # Updated
vp2_instant_ls_amount = "30000000000000" # 30M NTRN - UPDATED

# Valence Program 3: Gradual liquid stake
vp3_gradual_ls_receiver_address = "neutron1lr8pdcr3kgvljjt689a36a0pf6u92r223dy9nk84ks8fpkjw5fhqvfxep6" # Updated
vp3_gradual_ls_receiver_amount = "10000000000000" # 10M NTRN - UPDATED

# Valence Program 4: Bootstrap NTRN-dNTRN liquidity
vp4_bootstrap_liquidity_receiver_address = "neutron1wwyrj5nh8z4jvc36yugpy9f7sdx3d694faknkln673sf4xcs4apsvmwmz0" # Updated
vp4_bootstrap_liquidity_receiver_amount = "10000000000000" # 10M NTRN - UPDATED

# Actor addresses
# neutron DAO address
neutron_dao_addr = "neutron1kvxlf27r0h7mzjqgdydqdf76dtlyvwz6u9q8tysfae53ajv8urtq4fdkvy" # Updated

# List of address that are allowed to execute low security operations
operator_list = [
    "neutron14mlpd48k5vkeset4x7f78myz3m47jcax3ysjkp", # Updated this Keyne's dev wallet
    "neutron1ayw8xtxkty5cfzx44z6vxpevmtudg2n3d2sfz8", # Updated this to Udit's dev wallet
]
