owner = "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2"
init_lp_token_denom = "factory/neutron1fwlnsqt2vv3xhg96cy76avgwpa402zy2g49uwy2u7c2gshkp8hnqer9wgm/astroport/share"
usdc_dntrn_lp_token_denom = "factory/neutron1fwlnsqt2vv3xhg96cy76avgwpa402zy2g49uwy2u7c2gshkp8hnqer9wgm/astroport/share"
usdc_ntrn_pool_addr = ""
usdc_dntrn_pool_addr = ""
ntrn_denom = "untrn"
dntrn_denom = "factory/neutron1lzfk4aj26jz7gd3c4umxah9d22ezy8xfql677kev37vd0mq8y3tsn78saz/udntrn"
usdc_denom = ""
drop_liquid_staker_addr = "neutron18ecx6f2ywwnfxsql2l98jscw97lezczx8ax0g5wp8uj9rm95m0ls798cdq"
pool_max_spread = "0.5"
neutron_dao_addr = "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf"
security_dao_addr = "neutron10h9stc5v6ntgeygf5xf945njqq5h32r54rf7kf"
double_sided_min = "0.5"
double_sided_max = "2"
authorizations_allowed_list = [
    "neutron10h9stc5v6ntgeygf5xf945njqq5h32r54rf7kf",
    "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2",
    "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf",
]
