owner = ""
init_lp_token_denom = ""
usdc_dntrn_lp_token_denom = ""
usdc_ntrn_pool_addr = ""
usdc_dntrn_pool_addr = ""
ntrn_denom = ""
dntrn_denom = ""
usdc_denom = ""
drop_liquid_staker_addr = ""
pool_max_spread = ""
neutron_dao_addr = ""
security_dao_addr = ""
double_sided_min = ""
double_sided_max = ""
authorizations_allowed_list = [
    "",
    "",
]
