owner = "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2"
init_lp_token_denom = "factory/neutron1vvmfjgax752j55mz0y8eq9y3j9wc8ywxshql73e6wwuyv0ftuuuq5wfr0z/astroport/share"
usdc_dntrn_lp_token_denom = "factory/neutron1ta3dq7jekl77kmlc94ph3hwnahjv4n4u5tkxhfdx7ehrnje3hxaspx3phn/astroport/share"
usdc_ntrn_pool_addr = "neutron1vvmfjgax752j55mz0y8eq9y3j9wc8ywxshql73e6wwuyv0ftuuuq5wfr0z"
usdc_dntrn_pool_addr = "neutron1ta3dq7jekl77kmlc94ph3hwnahjv4n4u5tkxhfdx7ehrnje3hxaspx3phn"
ntrn_denom = "untrn"
dntrn_denom = "factory/neutron1lzfk4aj26jz7gd3c4umxah9d22ezy8xfql677kev37vd0mq8y3tsn78saz/udntrn"
usdc_denom = "factory/neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2/test-usdc"
drop_liquid_staker_addr = "neutron18ecx6f2ywwnfxsql2l98jscw97lezczx8ax0g5wp8uj9rm95m0ls798cdq"
pool_max_spread = "0.5"
neutron_dao_addr = "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2"
security_dao_addr = "neutron10h9stc5v6ntgeygf5xf945njqq5h32r54rf7kf"
double_sided_min = "0.5"
double_sided_max = "2"
authorizations_allowed_list = [
    "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf",
    "neutron1hl9vrr0k0l2pz62v343f50v0djm87dzhvxjtca",
]
