owner = "neutron1ayw8xtxkty5cfzx44z6vxpevmtudg2n3d2sfz8" # Updated this to Udit's dev wallet

# Denoms
# NTRN denom
ntrn_denom = "untrn"

# Drop staker core contract address
drop_liquid_staker_addr = "neutron1l8s4xge4s0hkvd8y7a8tkejakjmdcg0mhpst5sdufwfex2luhgrsugu0h8" 

# Forwarding configuration
## Max size of batch
max_amount_to_forward = "10000000000000"
## Interval in seconds between batches
interval_seconds_between_batches = "1"

# Actor addresses
# neutron DAO address
neutron_dao_addr = "neutron1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstdxvff"
# Security DAO address
security_dao_addr = "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2"
# List of address that are allowed to execute low security operations
operator_list = [
    "neutron14mlpd48k5vkeset4x7f78myz3m47jcax3ysjkp", # Updated this Keyne's dev wallet
    "neutron1ayw8xtxkty5cfzx44z6vxpevmtudg2n3d2sfz8", # Updated this to Udit's dev wallet
]
