owner = "neutron1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstdxvff" 

# Denoms
# NTRN denom
ntrn_denom = "untrn" 
# dNTRN denom
dntrn_denom = "factory/neutron1jz90vam2a4glwll770psh5tyg72k0kcvwtfrx4ysx2mac9ynv8rq0uevh9/udntrn" 

# Bootstrap program dNTRN receive address
vp4_bootstrap_liquidity_receiver_addr = "neutron1hrmh83zhash3yll59x53t6nn7mrms6s0ltxhcd8z8ngu3hppwveqfhlahh"

# Drop staker core contract address
drop_liquid_staker_addr = "neutron1l8s4xge4s0hkvd8y7a8tkejakjmdcg0mhpst5sdufwfex2luhgrsugu0h8" 

# Split ratios
## To send to Neutron DAO (100M dNTRN)
ntrn_dao_split_normalized_fraction = "0.8"
## To send to vp4 to bootstrap liquidity (25M dNTRN)
vp4_receiver_split_normalized_fraction = "0.2"


# Actor addresses
## Neutron DAO address
neutron_dao_addr = "neutron1suhgf5svhu4usrurvxzlgn54ksxmn8gljarjtxqnapv8kjnp4nrstdxvff" 
## Security DAO address
security_dao_addr = "neutron13j84x6gyv2n7kcpcy59g9xz3efy375wr4tjywp"
## Addresses allowed to execute low security actions 
operator_list = [
    "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2",
]