owner = "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2"
ntrn_denom = "untrn"
dntrn_denom = "factory/neutron1lzfk4aj26jz7gd3c4umxah9d22ezy8xfql677kev37vd0mq8y3tsn78saz/udntrn"
bootstrap_ntrn_dntrn_receive_addr = "neutron1mjexzk2fh92dz60mrm5cdcls23xm3s5yvs0u4vaz9685av3sfepqn04ap9"
drop_liquid_staker_addr = "neutron18ecx6f2ywwnfxsql2l98jscw97lezczx8ax0g5wp8uj9rm95m0ls798cdq"
drop_liquid_unstaker_addr = "neutron18ecx6f2ywwnfxsql2l98jscw97lezczx8ax0g5wp8uj9rm95m0ls798cdq"
drop_withdrawal_manager_addr = "neutron15x6m8kxvufgzfy74c4kunrkh6y7hwxgnnc4tfc4hwt3cy0j6zs2skk07xn"
voucher_addr = "neutron1hdedwnjwk8r22hrujdh79966hu50zthgvatu4ju075lyt5sa9lvq5yd3fs"
neutron_dao_addr = "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf"
security_dao_addr = "neutron10h9stc5v6ntgeygf5xf945njqq5h32r54rf7kf"
authorizations_allowed_list = [
    "neutron10h9stc5v6ntgeygf5xf945njqq5h32r54rf7kf",
    "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2",
    "neutron14xcrdjwwxtf9zr7dvaa97wy056se6r5erln9pf",
]
