owner = "neutron1phx0sz708k3t6xdnyc98hgkyhra4tp44et5s68"
ntrn_denom = "untrn"
bootstrap_program_receiver=""
stake_ntrn_program_receiver=""
# Neutron DAO address
neutron_dao_addr = "" 
# Security DAO address
security_dao_addr = ""
authorizations_allowed_list = [
    "",
]

# The amount to send to the bootstrap program
ntrn_split_to_bootstrap_program_fixed_amount = ""
# The amount to send to the stake ntrn program
ntrn_split_to_stake_program_fixed_amount = ""