# Owner can make arbitrary changes to the program. In production, this must be the Neutron DAO address
owner = "neutron1ayw8xtxkty5cfzx44z6vxpevmtudg2n3d2sfz8" # Updated this to Udit's dev wallet

# Token denoms of various tokens
ntrn_denom = "untrn"
dntrn_denom = "factory/neutron1ytalpjvxz7njekfep97sss2s83ezw6q8lt9spsvnd2d43ygys9gssy7ept/udntrn" # changed
usdc_denom = "factory/neutron19glux3jzdfyyz6ylmuksgxfj5phdaxfr2uhy86/usdc" # changed
usdc_ntrn_lp_denom = "factory/neutron16puus9vjwq4xq0pkl59x30qwn5t48t7r90zqcgc5g8qsyu0u0fnskraxld/astroport/share" # changed

# USDC-NTRN lp tokens are batched and forwarded. 
# The batch size and interval needs to be configured
usdc_ntrn_lp_max_batch_size = "100000000000"
usdc_ntrn_lp_batch_interval_seconds = "1"

# USDC-NTRN pool configuration
# The program will withdraw liquidity from this pool
usdc_ntrn_pool_addr = "neutron16puus9vjwq4xq0pkl59x30qwn5t48t7r90zqcgc5g8qsyu0u0fnskraxld" # changed

# Drop Staking configuration
drop_liquid_staker_addr = "neutron1wu9ng2pphg4g0a9d7ptq9ufqpcc7glhay33nhj79z4xs97qstj4q6un25a" # changed

# Liquidity provisioning configuration
usdc_dntrn_pool_addr = "neutron1faz0e5wugx23c03pa85alslvhyge8xk9hxwlyltjhn7zttng4n2qqpjl4m" # changed
# Minimum pool ratio (AssetA/AssetB) required to provide double sided liquidity (e.g., 0.9)
expected_pool_ratio_min = "0.015" # changed
# Maximum pool ratio (AssetA/AssetB) required to provide double sided liquidity (e.g., 1.1)
expected_pool_ratio_max = "0.030" # changed
# If we are providing single sided liquidity, half the tokens will be swapped for the other denomination.
# Pool max spread is the acceptable spread in the pool while swapping tokens.
pool_max_spread = "0.05" # changed

# Actor addresses
# neutron DAO address
neutron_dao_addr = "neutron1kvxlf27r0h7mzjqgdydqdf76dtlyvwz6u9q8tysfae53ajv8urtq4fdkvy" # changed
# Security DAO address
security_dao_addr = "neutron1m9l358xunhhwds0568za49mzhvuxx9ux8xafx2"
# List of address that are allowed to execute low security operations
operator_list = [
    "neutron14mlpd48k5vkeset4x7f78myz3m47jcax3ysjkp", # Updated this to Keyne's dev wallet
    "neutron1ayw8xtxkty5cfzx44z6vxpevmtudg2n3d2sfz8", # Updated this to Udit's dev wallet 
] 

# You should not need to modify below. These should be set to very large values so all tokens are forwarded/returned.
# USDC forwarder max amount configuration
usdc_forwarder_max_amount = "1000000000000" # Set this to 1 million usdc
# Return forwarder max amount configuration
return_forwarder_max_amount = "1000000000000" # Set this to 1 million
