[contracts]

[contracts.code_ids.neutron]
# Registry is not used and only needed on neutron
valence_program_registry         = 53
valence_authorization            = 56
valence_processor                = 57
valence_base_account             = 58
valence_forwarder_library        = 59
valence_splitter_library         = 60
valence_reverse_splitter_library = 61
valence_astroport_lper           = 62
valence_astroport_withdrawer     = 63

valence_drop_liquid_staker       = 54
valence_drop_liquid_unstaker     = 55