[contracts]

[contracts.code_ids.neutron]
# Registry is not used and only needed on neutron
valence_program_registry         = 65
valence_authorization            = 45
valence_processor                = 46
valence_base_account             = 47
valence_forwarder_library        = 48
valence_splitter_library         = 49
valence_reverse_splitter_library = 50
valence_astroport_lper           = 51
valence_astroport_withdrawer     = 52

valence_drop_liquid_staker       = 72
valence_drop_liquid_unstaker     = 73